"use client";

import React from "react";
import Link from "next/link";
import { useApp } from "../context/AppContext";
import { Globe, Share2, Mail, ShieldAlert } from "lucide-react";

export default function Footer() {
  const { language, t } = useApp();

  return (
    <footer className="w-full bg-slate-900 border-t border-slate-800 text-slate-400 py-12 px-4 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl">
        
        {/* Top Grid section */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 pb-8 border-b border-slate-800">
          
          {/* Logo and Description */}
          <div className="space-y-4 col-span-1 md:col-span-2">
            <Link href="/" className="flex items-center gap-2 select-none">
              <div className="bg-white p-1 rounded-lg inline-block">
                <img 
                  src="/logo.png" 
                  alt="بُعد بنيان" 
                  className="h-10 w-auto object-contain max-w-[160px]" 
                />
              </div>
            </Link>
            <p className="text-xs text-slate-400 max-w-sm leading-relaxed">
              {language === "ar" 
                ? "منصة بُعد بنيان متخصصة في مساعدة المهندسين وأصحاب المشاريع على مراجعة المخططات ومطابقتها تقنياً للاشتراطات الفنية قبل التشييد باستخدام تقنيات محاكاة التوأم الرقمي ثلاثي الأبعاد."
                : "The بُعد بنيان platform specializes in helping engineers and project owners review blueprints and technically align them with zoning regulations before construction using 3D digital twin simulation."}
            </p>
          </div>

          {/* Site Pages Links */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">
              {language === "ar" ? "روابط المنصة" : "Platform Links"}
            </h4>
            <ul className="space-y-2 text-xs">
              <li>
                <Link href="/" className="hover:text-white transition-colors">{t.nav.home}</Link>
              </li>
              <li>
                <Link href="/services" className="hover:text-white transition-colors">{t.nav.services}</Link>
              </li>
              <li>
                <Link href="/pricing" className="hover:text-white transition-colors">{t.nav.pricing}</Link>
              </li>
              <li>
                <Link href="/support" className="hover:text-white transition-colors">{t.nav.support}</Link>
              </li>
            </ul>
          </div>

          {/* Contact & Socials */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">
              {language === "ar" ? "قنوات التواصل" : "Contact channels"}
            </h4>
            <div className="text-xs space-y-2">
              <p className="flex items-center gap-1.5 hover:text-white transition-colors cursor-pointer">
                <Mail className="h-4 w-4 text-compliance-green" />
                <span>info@boadbunyan.sa.mock</span>
              </p>
              <div className="flex gap-3 pt-2">
                <a href="#mock-tw" className="p-2 rounded-full bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700 transition-colors">
                  <Globe className="h-4 w-4" />
                </a>
                <a href="#mock-in" className="p-2 rounded-full bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700 transition-colors">
                  <Share2 className="h-4 w-4" />
                </a>
              </div>
            </div>
          </div>
        </div>

        {/* Disclaimer Panel */}
        <div className="mt-6 p-4 rounded-lg bg-slate-950 border-l-4 border-accent-gold text-slate-300 text-xs flex gap-3 items-start">
          <ShieldAlert className="h-5 w-5 text-accent-gold flex-shrink-0 mt-0.5" />
          <div>
            <h5 className="font-bold text-white mb-1">
              {language === "ar" ? "إخلاء مسؤولية استرشادي" : "Advisory Disclaimer"}
            </h5>
            <p className="leading-relaxed">
              {language === "ar" 
                ? "جميع نتائج الفحص والمراجعة الصادرة من منصة «بُعد بنيان» هي نتائج استرشادية فنية لغرض المساعدة الذاتية فقط، ولا تشكّل أو تغني عن الاعتماد الرسمي أو الموافقة الحكومية من وزارة الشؤون البلدية والقروية والإسكان أو الأمانات أو منصة بلدي الرسمية."
                : "All review and compliance results generated by the «بُعد بنيان» platform are technical guidelines for self-assistance only, and do not constitute or replace official approvals or municipal permits from the Ministry of Municipal and Rural Affairs or the official Balady portal."}
            </p>
          </div>
        </div>

        {/* Bottom Rights Section */}
        <div className="mt-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-[10px] text-slate-500">
          <p>© {new Date().getFullYear()} {language === "ar" ? "بُعد بنيان. جميع الحقوق محفوظة" : "بُعد بنيان. All rights reserved."}</p>
          <div className="flex gap-4">
            <a href="#privacy" className="hover:text-slate-400 transition-colors">
              {language === "ar" ? "سياسة الخصوصية" : "Privacy Policy"}
            </a>
            <a href="#terms" className="hover:text-slate-400 transition-colors">
              {language === "ar" ? "الشروط والأحكام" : "Terms & Conditions"}
            </a>
          </div>
        </div>
        
      </div>
    </footer>
  );
}
